### ISSUE TITLE
matchengine kafka topic不可配置

### ISSUE THREAD

**Issue by canghai118** [viabtc/viabtc_exchange_server#100]
matchenine会向kafka中写入数据，然而写入的topic名字是[代码中写死](https://github.com/viabtc/viabtc_exchange_server/blob/master/matchengine/me_message.c#L97)的。而作为topic的消费者，marketprice, accessws服务器，topic的名字是配置文件中可配置的。 是否是matchengine疏忽了？

**Comment by haipome** [comment]
作为生产者，写死是没有问题的。topic 消费者可配，只要是为了是线上的方便。
