### ISSUE TITLE
sql注入风险

### ISSUE THREAD

**Issue by shanhuhai5739** [viabtc/viabtc_exchange_server#101]
sql = sdscatprintf(sql, "INSERT INTO `%s` (`id`, `t`, `side`, `create_time`, `update_time`, `user_id`, `market`, "
                    "`price`, `amount`, `taker_fee`, `maker_fee`, `left`, `freeze`, `deal_stock`, `deal_money`, `deal_fee`) VALUES ", table);

这种类似字符串拼写的sql有sql注入的风险

**Comment by tornodo** [comment]
这个服务只给前端服务暴露api接口，前端又有前端的验证逻辑，到了这里就没有什么威胁了
