### ISSUE TITLE
数据库表结构

### ISSUE THREAD

**Issue by gutongjiang** [viabtc/viabtc_exchange_server#102]
trade_history下每新增一个用户都要添加5张表, 为什么要这么设计呢, 为什么不一张表对应多个用户

**Comment by rqzrqh** [comment]
数据库分表，降低竞争。


| |
rqzrqh
邮箱：rqzrqh@163.com
|

Signature is customized by Netease Mail Master

在2018年06月27日 19:34，Fei Chen 写道：

trade_history下每新增一个用户都要添加5张表, 为什么要这么设计呢, 为什么不一张表对应多个用户

**Comment by gutongjiang** [comment]
如果用户量增大呢, 百万级用户就有百万张表, mysql可以支撑吗

**Comment by rqzrqh** [comment]
按照用户分了100张表，百万级用户分摊下来每张表几万人，其中成交再以用户id建索引，查询速度没问题的。如果担心速度慢并且预计能到百万用户可以分1000张表


| |
rqzrqh
邮箱：rqzrqh@163.com
|

Signature is customized by Netease Mail Master

在2018年06月27日 19:39，Fei Chen 写道：

如果用户量增大呢, 百万级用户就有百万张表, mysql可以支撑吗

**Comment by NOAChainTeam** [comment]
如果数据库的集群方案用 tidb的话，用户表的是不是就不用 拆成 多张表了？

**Comment by paizzj** [comment]
如果数据库集群方案用tidb， 用户相关的表是不是就不用拆成 多张表了？

**Comment by rqzrqh** [comment]
不了解tidb，而且实际上matchengine我只用它做撮合，只记了快照，报盘是通过外部系统实现的，报盘和结算上记了订单和成交。


| |
rqzrqh
邮箱：rqzrqh@163.com
|

Signature is customized by Netease Mail Master

在2018年06月27日 19:53，pisa 写道：

如果数据库集群方案用tidb， 用户相关的表是不是就不用拆成 多张表了？

**Comment by wh0am111** [comment]
> 数据库集群方案

数据库集群方案有什么推荐的吗？请问
