### ISSUE TITLE
websocket api 本地测试该怎么部署

### ISSUE THREAD

**Issue by fourseaLee** [viabtc/viabtc_exchange_server#105]
我用websocket 在线测试，一直都连接不上。
"auth_url": "http://192.168.1.6:8000/internal/exchange/user/auth",
 "sign_url": "http://192.168.1.6:8000/internal/exchange/user/api/auth",
是否是由于以上两个地址影响的，但是这两个地址应该怎么配置？是独立于这个引擎外的服务器吗

**Comment by fourseaLee** [comment]
我好像明白了，我将accessws中的config.json中的“stream@/tmp/accessws.sock” 改成“tcp@0.0.0.0:8090”再用websocket的对外地址是“你的ip:8090”就可以在线测试了。

**Comment by yin273642232** [comment]
你可以使用nginx来代理websocket。

upstream unix_accessws_server {
    server unix:/dev/shm/accessws.sock;
}

server {
    listen      80 default_server;
    server_name mydomain.com;
    root        /www/html/accessws/;
    location    / {
        index index.html;
        proxy_pass   http://unix_accessws_server;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

**Comment by TaylorWenOne** [comment]
> accessws

没太理解你的意思，websocket这个链接必须要用nginx代理吗，还是可以直接改配置文件里的svr，monitor需要改吗？

**Comment by wh0am111** [comment]
请问websocket的防跨域有弄吗，怎么弄的呢？

**Comment by TaylorWenOne** [comment]
via中有个auth.php的配置



---原始邮件---
发件人: "wh0am111"<notifications@github.com&gt;
发送时间: 2020年8月5日(周三) 上午10:14
收件人: "viabtc/viabtc_exchange_server"<viabtc_exchange_server@noreply.github.com&gt;;
抄送: "TaylorWenOne"<284726777@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [viabtc/viabtc_exchange_server] websocket api 本地测试该怎么部署 (#105)




 
请问websocket的防跨域有弄吗，怎么弄的呢？

**Comment by wh0am111** [comment]
> via中有个auth.php的配置
> […](#)
> ---原始邮件--- 发件人: "wh0am111"<notifications@github.com&gt; 发送时间: 2020年8月5日(周三) 上午10:14 收件人: "viabtc/viabtc_exchange_server"<viabtc_exchange_server@noreply.github.com&gt;; 抄送: "TaylorWenOne"<284726777@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [viabtc/viabtc_exchange_server] websocket api 本地测试该怎么部署 (#105) 请问websocket的防跨域有弄吗，怎么弄的呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

请问在哪里呢？

**Comment by yuexia-martin** [comment]
请教下 Websocket 有需要鉴权的

**Comment by TaylorWenOne** [comment]
具体?



---原始邮件---
发件人: "yuexia-martin"<notifications@github.com&gt;
发送时间: 2020年9月2日(周三) 中午12:01
收件人: "viabtc/viabtc_exchange_server"<viabtc_exchange_server@noreply.github.com&gt;;
抄送: "TaylorWenOne"<284726777@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [viabtc/viabtc_exchange_server] websocket api 本地测试该怎么部署 (#105)




 
请教下 Websocket 有需要鉴权的

**Comment by yuexia-martin** [comment]
请教下 Websocket 有需要鉴权的 例如:{"id":1,"method":"order.history","params":["BTCBCH",0,99999999,0,50]} 就返回 {"error": {"code": 6, "message": "require authentication"}, "result": null, "id": 1} 这种权限鉴定我抓包到是通过"auth_url": "http://192.168.1.6:8000/internal/exchange/user/auth",
"sign_url": "http://192.168.1.6:8000/internal/exchange/user/api/auth", 这里弄的 但是这里怎么部署啊？ 请教大神
