### ISSUE TITLE
accessws是如何提供WEBSOCKET服务器的？

### ISSUE THREAD

**Issue by yunhui0501** [viabtc/viabtc_exchange_server#109]
大家好，请问这个accessws模块提供websocket服务，IP和端口是如何设置的？谢谢

**Comment by yunhui0501** [comment]
搞定了，谢谢杨总。

**Comment by TaylorWenOne** [comment]
> 大家好，请问这个accessws模块提供websocket服务，IP和端口是如何设置的？谢谢

能把你的方案放出来给大家看看吗

**Comment by nicett** [comment]
> > 大家好，请问这个accessws模块提供websocket服务，IP和端口是如何设置的？谢谢
> 
> 能把你的方案放出来给大家看看吗

这个问题你解决了吗?

**Comment by sevenMonkey** [comment]
麻烦请假一下，websocket的服务是怎么搭建起来的。 谢谢！
