### ISSUE TITLE
Balance.Update issue

### ISSUE THREAD

**Issue by ohld** [viabtc/viabtc_exchange_server#121]
Hi there!

I just run into your exchange server and it seems to be very awesome! Unfortunately, like many other opensourced great projects it suffers from the lack of documentation. 

I've tried to make REST api requests to play with the exchange. I've found Wiki pages [here](https://github.com/viabtc/viabtc_exchange_server/wiki). Some of queries are gone right:
``` python
import requests, json

ip_exchange = "http://localhost:8080/"  # right port forwarding  
headers = {'content-type': 'application/json'}

params = {
    "method": "balance.query",
    "params":  [1, "BTC"],
    "jsonrpc": "2.0",
    "id": 0,
}

response = requests.post(ip_exchange, json=params, headers=headers)
print(json.loads(response.text))
```
Response:
``` python
{'result': {'BTC': {'freeze': '0', 'available': '0'}}, 'error': None, 'id': 0}
```

But some of others are not:
``` python
import requests, json

ip_exchange = "http://localhost:8080/"  # right port forwarding  
headers = {'content-type': 'application/json'}

params = {
    "method": "balance.update",
    "params":  [1, "BTC", "deposit", 100, "1.2345"],
    "jsonrpc": "2.0",
    "id": 0,
}

response = requests.post(ip_exchange, json=params, headers=headers)
print(json.loads(response.text))
```
Response:

``` python
{'result': None, 'error': {'code': 1, 'message': 'invalid argument'}, 'id': 0}
```

Can someone point out what I've done wrong (or just the documentation is outdated).

If someone can share any code samples describing how to query this exchange server, how to add users / tokens, that wound be very useful for the community. Thanks.

**Comment by yin273642232** [comment]
params = {
    "method": "balance.update",
    "params":  [1, "BTC", "deposit", 100, "1.2345", {"mykey": "myval"}],
    "jsonrpc": "2.0",
    "id": 0,
}
-------------
{"mykey": "myval"} Is customize json object，must exist and not empty

**Comment by ohld** [comment]
@yin273642232 Thank you very much! I'll try it. There are no argument like this in Wiki pages.
For what we may need this argument?

**Comment by ohld** [comment]
@yin273642232 Thanks! I've tried with {} as an argument and it returned:
``` python
{'result': {'status': 'success'}, 'error': None, 'id': 0}
```
