### ISSUE TITLE
How to add new currency

### ISSUE THREAD

**Issue by ohld** [viabtc/viabtc_exchange_server#124]
The result of `asset.summary` API call shows the available currencies:
``` python
{'result': [
    {'name': 'ETH', 'freeze_balance': '0', 'total_balance': '0', 'available_count': 0, 'available_balance': '0', 'freeze_count': 0}, 
    {'name': 'BTC', 'freeze_balance': '0', 'total_balance': '0', 'available_count': 0, 'available_balance': '51.415', 'freeze_count': 2}, 
    {'name': 'BCH', 'freeze_balance': '0', 'total_balance': '0', 'available_count': 0, 'available_balance': '0', 'freeze_count': 0}, 
    {'name': 'LTC', 'freeze_balance': '0', 'total_balance': '0', 'available_count': 0, 'available_balance': '0', 'freeze_count': 0},
    {'name': 'DASH', 'freeze_balance': '0', 'total_balance': '0', 'available_count': 0, 'available_balance': '0', 'freeze_count': 0}
], 'error': None, 'id':0}
```

That means only ETH, BTC, LTC, DASH are available. How to add / remove currencies? Thanks

**Comment by ohld** [comment]
Here: https://github.com/viabtc/viabtc_exchange_server/blob/f4a1ae3a5f01278cdb689fc7c021d45dace26cf3/matchengine/config.json

**Comment by TaylorWenOne** [comment]
> Here: https://github.com/viabtc/viabtc_exchange_server/blob/f4a1ae3a5f01278cdb689fc7c021d45dace26cf3/matchengine/config.json

oh no,only change the config.json?that means i need login import service machine and change the cofing file,then restart matchengine when i need add a new currency every time，there are  thousand currencys...
