### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [viabtc/viabtc_exchange_server#13]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [update_dict_key_dup](https://github.com/viabtc/viabtc_exchange_server/blob/15d4be46ee151d9eb98377878eafcbb7b822d315/matchengine/me_update.c#L36)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex") ⇒ [dlog_init](https://github.com/viabtc/viabtc_exchange_server/blob/15d4be46ee151d9eb98377878eafcbb7b822d315/utils/ut_log.c#L368)

**Comment by haipome** [comment]
Good point. I should do it more completely.

About the malloc function, I did't not check the return value because when malloc fail, just let the process crash and restart is better. I always check the malloc return value in base library network and utils.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by haipome** [comment]
Sure.

I think I need more obviously let the process crash when malloc fail.
