### ISSUE TITLE
What's the source code licence terms?

### ISSUE THREAD

**Issue by trustfarm-dev** [viabtc/viabtc_exchange_server#14]
Hi,

there's no license terms in your whole source code.
example, what I'm saying is MIT or Apache or GPL or LGPL or ...
Or, Your company internal license term.

It may be freely studying use now.
Source code has opened but, Licenses are still live. 
So you can describe exact source code license terms in your souce code.

Good study materials.
thanks.

**Comment by rmtew** [comment]
The license is right there, in the source code.  Take a look.

**Comment by trustfarm-dev** [comment]
@rmtew  where's exact license terms? there's only source code owner's term only.
/*
 * Description: 
 *     History: yang@haipo.me, 2016/04/19, create
 */

So, If some one , some company use this source , then he will claim? 
or freely modify of this code then author no concern?

that is not clear.

**Comment by rmtew** [comment]
Look in the top level! There's a file called LICENSE.

**Comment by trustfarm-dev** [comment]
@rmtew Great!.
It is sad story to you closing the ViaBTC, But, Open your technology is great works.
Good Luck!

**Comment by rmtew** [comment]
Maybe look a bit harder there too :-)  Repository owner is @haipome, I have
nothing to do with Viabtc.

**Comment by trustfarm-dev** [comment]
@rmtew  It's not important thing I think. because source code and this repo's owner is @haipome , very clear.
You instruct me to where's licence term file. your instruction helps I finding the term file easily and in a short time. that's your thanks.
And Cheering the technology Contribution to owner. it is also very clear, even though I've wrote another thread.

Anyway thanks and good luck to all.
