### ISSUE TITLE
Recommend log , balance server from MySQL to NoSQL DB.

### ISSUE THREAD

**Issue by trustfarm-dev** [viabtc/viabtc_exchange_server#15]
I think MySQL server using the store logs, user balances, important imformation.
It will used NoSQL based backend (eg. mongodb , ... ) for scalabilities and securities .
using the sharding and replication technology.
MySQL is Popular using R-DBMS and Also secure , but it's central and websites store passwd.
It's hard to expanding and backuping the data , in realtime.

**Comment by haipome** [comment]
Partly right. The MySQL used to store oper log and history data. User balance did not store in MySQL, it was in memory.

**Comment by trustfarm-dev** [comment]
@haipome  If break or suddenly down server, then user balance will not atomic store and serialization problem I think.

**Comment by haipome** [comment]
If you have read the code, it use thread pool to write to MySQL. It won't break the server.
