### ISSUE TITLE
time difference api usage.

### ISSUE THREAD

**Issue by trustfarm-dev** [viabtc/viabtc_exchange_server#16]
https://github.com/viabtc/viabtc_exchange_server/blob/3da9c872bc4b53a5f58e9254aeee2550c972a512/utils/ut_log.c#L90

in case of unix based time api has lack of limitation, wrap-around cases happen.
at normal time , it is not a problem. 
but, we don't know the future.
So, there's recommendation way and api proposed by Posix and GNU.

Here's link.
http://www.gnu.org/software/libc/manual/html_node/Elapsed-Time.html

**Comment by haipome** [comment]
The time_t is a long int type, it is 64 bit in x86-64 machine. This should be enough.

**Comment by trustfarm-dev** [comment]
Code should be learned from history.
in year 1999 ~ 2000 , programmer met millenium bugs. @  :-)
