### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by yunhui0501** [viabtc/viabtc_exchange_server#163]
order.depth 一秒钟请求40个交易对的信息，发现accesshttp和matchengine.exe的内存一点一点的涨，请问大家有没有遇到过？

**Comment by yunhui0501** [comment]
static void svr_on_recv_pkg(nw_ses * ses, rpc_pkg * pkg)
这个函数中的json_t *params 在异常的时候释放了，在正常的流程中，好像没有看到释放的动作？是不是有问题？

**Comment by yunhui0501** [comment]
还有一个变量 sds params_str好像也没有释放

**Comment by objectt** [comment]
They are released/freed in the cleanup section.
