### ISSUE TITLE
marketprice not work

### ISSUE THREAD

**Issue by hiluoyun** [viabtc/viabtc_exchange_server#172]
### process is alive
![image](https://user-images.githubusercontent.com/13412717/53537593-71d3d100-3b45-11e9-9301-51704985ad5e.png)

### accesshttp.log
![image](https://user-images.githubusercontent.com/13412717/53537635-9cbe2500-3b45-11e9-8adf-ab4a6656d63d.png)

### marketprice.log
![image](https://user-images.githubusercontent.com/13412717/53537747-f1fa3680-3b45-11e9-8034-f6f06ce35e36.png)

### marketprice cpu !!!

![image](https://user-images.githubusercontent.com/13412717/53632936-1db61300-3c51-11e9-8e5e-c3623afc3ad7.png)

**force kill marketprice process and restart , it is work!**
please help me, thanks!

The same problem happened again today, and I followed it up.

### pstack 24717
![image](https://user-images.githubusercontent.com/13412717/53730925-396d2380-3eb4-11e9-9ca5-86ef9dbc395a.png)
![image](https://user-images.githubusercontent.com/13412717/53730945-48ec6c80-3eb4-11e9-94c4-4033c3824845.png)

**Comment by objectt** [comment]
can you provide more logs?

**Comment by hiluoyun** [comment]
> can you provide more logs?

![image](https://user-images.githubusercontent.com/13412717/53775999-86daa680-3f2f-11e9-9562-548dfd35526c.png)
I've found out why, when you pass in an inappropriate timestamp, the function goes into a dead loop.
So it's easy to fix the problem.
