### ISSUE TITLE
如何配置实现多个交易对市场  比如 BTCUSDT,BTCETH,BTCBCH

### ISSUE THREAD

**Issue by muyang93** [viabtc/viabtc_exchange_server#174]
我这样配置发现启动会报错
"markets": [{
            "name": "BTCUSDT",
            "stock": {
                "name": "BTC",
                "prec": 8
            },
            "money": {
                "name": "USDT",
                "prec": 8
            },
            "min_amount": "0.001"
        }, {
            "name": "OGCUSDT",
            "stock": {
                "name": "OGC",
                "prec": 8
            },
            "money": {
                "name": "USDT",
                "prec": 8
            },
            "min_amount": "0.001"
        },{
            "name": "OGCETH",
            "stock": {
                "name": "OGC",
                "prec": 8
            },
            "money": {
                "name": "ETH",
                "prec": 8
            },
            "min_amount": "0.001"
        }, {
            "name": "BTCETH",
            "stock": {
                "name": "BTC",
                "prec": 8
            },
            "money": {
                "name": "ETH",
                "prec": 8
            },
            "min_amount": "0.001"
        }

    ],

**Comment by ohld** [comment]
I've solved this. Take a look at how I did it here: howhttps://github.com/testnet-exchange/viabtc_exchange_server

**Comment by lealife** [comment]
首先配置assets, precSave 配大点, 比如20

**Comment by muyang93** [comment]
> 首先配置资产，prec_save配大点，比如20

确实是这样

**Comment by csxiaodiao** [comment]
@muyang93 config 文件能共享么 ：）

**Comment by lealife** [comment]
看看默认的样例就知道了

**Comment by csxiaodiao** [comment]
@lealife 加了个market，docker跑起来直接取不到东西了 --

**Comment by muyang93** [comment]
> @muyang93 config 文件能共享么 ：）

{
    "debug": true,
    "process": {
        "file_limit": 1000000,
        "core_limit": 1000000000
    },
    "log": {
        "path": "/var/log/trade/matchengine",
        "flag": "fatal,error,warn,info,debug,trace",
        "num": 10
    },
    "alert": {
        "host": "matchengine",
        "addr": "127.0.0.1:4444"
    },
    "svr": {
        "bind": [
            "tcp@0.0.0.0:7316",
            "udp@0.0.0.0:7316"
        ],
        "buf_limit": 100,
        "max_pkg_size": 10240,
        "heartbeat_check": false
    },
    "cli": "tcp@127.0.0.1:7317",
    "db_log": {
        "host": "localhost",
        "user": "root_trade",
        "pass": "123456",
        "name": "trade_log"
    },
    "db_history": {
        "host": "localhost",
        "user": "root_trade",
        "pass": "123456",
        "name": "trade_history"
    },
    "assets": [{
        "name": "USDT",
        "prec_save": 20,
        "prec_show": 8
    }, {
        "name": "ETH",
        "prec_save": 20,
        "prec_show": 8
    }, {
        "name": "BTC",
        "prec_save": 12,
        "prec_show": 8
    }, {
        "name": "OGC",
        "prec_save": 12,
        "prec_show": 8
    }],
    "markets": [{
        "name": "BTCUSDT",
        "stock": {
            "name": "BTC",
            "prec": 8
        },
        "money": {
            "name": "USDT",
            "prec": 8
        },
        "min_amount": "0.001"
    }, {
        "name": "OGCUSDT",
        "stock": {
            "name": "OGC",
            "prec": 8
        },
        "money": {
            "name": "USDT",
            "prec": 8
        },
        "min_amount": "0.001"
    }, {
        "name": "BTCETH",
        "stock": {
            "name": "BTC",
            "prec": 8
        },
        "money": {
            "name": "ETH",
            "prec": 8
        },
        "min_amount": "0.001"
    }, {
        "name": "OGCETH",
        "stock": {
            "name": "OGC",
            "prec": 8
        },
        "money": {
            "name": "ETH",
            "prec": 8
        },
        "min_amount": "0.001"
    }],
    "brokers": "127.0.0.1:9092",
    "slice_interval": 3600,
    "slice_keeptime": 259200
}

**Comment by csxiaodiao** [comment]
@muyang93 :) 可以了，谢谢

**Comment by wh0am111** [comment]
> 首先配置assets, prec_save 配大点, 比如20

请问 prec_save 和 prec_show 两个配置是什么意思
