### ISSUE TITLE
Needs memory allocation check

### ISSUE THREAD

**Issue by trustfarm-dev** [viabtc/viabtc_exchange_server#18]
https://github.com/viabtc/viabtc_exchange_server/blob/3da9c872bc4b53a5f58e9254aeee2550c972a512/readhistory/rh_server.c#L207

**Comment by haipome** [comment]
This call should not fail. If fail, just let it crash is better.

**Comment by trustfarm-dev** [comment]
DV (Design Verification) :  when developing crash or dead as soon as faster is clearly better, also we make it to dead easily special condition.
But  PV (Product Verification) and Production : it doesn't.
