### ISSUE TITLE
走marketprice的接口返回空数据

### ISSUE THREAD

**Issue by klpeng** [viabtc/viabtc_exchange_server#182]
ERR_RET_LN(add_handler("market.last", marketprice, CMD_MARKET_LAST));
    ERR_RET_LN(add_handler("market.deals", marketprice, CMD_MARKET_DEALS));
    ERR_RET_LN(add_handler("market.kline", marketprice, CMD_MARKET_KLINE));
    ERR_RET_LN(add_handler("market.status", marketprice, CMD_MARKET_STATUS));
    ERR_RET_LN(add_handler("market.status_today", marketprice, CMD_MARKET_STATUS_TODAY));
上述这些接口都返回空数据，请教大家是什么原因

**Comment by lealife** [comment]
Kafka安装有问题

**Comment by chenluyong** [comment]
kafka与marketprice没有连接好

**Comment by chenluyong** [comment]
#192 
market.kline return null
