### ISSUE TITLE
`accessws` auth\sign service not find (accessws模块依赖的服务不存在)

### ISSUE THREAD

**Issue by chenluyong** [viabtc/viabtc_exchange_server#185]
config.json
```
"auth_url": "http://192.168.1.6:8000/internal/exchange/user/auth",
"sign_url": "http://192.168.1.6:8000/internal/exchange/user/api/auth",
```

---

In ` on_job ` function used in ` auth_url ` parameter service content
We didn't in the corresponding application services ` viabtc_exchange_server `

---

在`on_job`函数中使用 `auth_url`参数的服务内容
而这个服务对应的应用程序却没有在 `viabtc_exchange_server`中

**Comment by lawrence296** [comment]
"auth_url" - the purpose of this function is for "viabtc" to validate a user that is registered in your front-end application. You have to build the validation logic in your front-end application.
