### ISSUE TITLE
[error]ut_kafka.c:27(on_logger): RDKAFKA-3-FAIL: rdkafka#consumer-1: [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/bootstrap: Receive failed: Disconnected

### ISSUE THREAD

**Issue by klpeng** [viabtc/viabtc_exchange_server#186]
[error]ut_kafka.c:27(on_logger): RDKAFKA-3-FAIL: rdkafka#consumer-1: [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/bootstrap: Receive failed: Disconnected

**Comment by lealife** [comment]
kafka stated ?

**Comment by qyangdu** [comment]
It is Kafka been reconnected, normally it can be ignored safely.
