### ISSUE TITLE
same result , but it's not expandable code.

### ISSUE THREAD

**Issue by trustfarm-dev** [viabtc/viabtc_exchange_server#19]
https://github.com/viabtc/viabtc_exchange_server/blob/3da9c872bc4b53a5f58e9254aeee2550c972a512/matchengine/me_market.c#L42

```
struct dict_order_key {
    uint64_t    order_id;
};
...

static void *dict_order_key_dup(const void *key)
{
    struct dict_order_key *obj = malloc(sizeof(struct dict_order_key));
    memcpy(obj, key, sizeof(struct dict_order_key));
    return obj;
}
```

1. no consistency of codes, some where checking null , some where not.
2. it's recommended the member variable copy.  obj->order_id = key->order_id 
in future you expand struct , then this code will be more safe and expandable easily.

**Comment by haipome** [comment]
1. In base library, network and utils, it always check the null return. But in upper layer, the malloc or function base on malloc should not return null, if happens, make it crash is better. Also check null return will make the code more complex.

2. memcpy is more expandable I think.
