### ISSUE TITLE
Need to clarify speed of the server

### ISSUE THREAD

**Issue by egorsmkv** [viabtc/viabtc_exchange_server#190]
The readme says that the server has speed about 10K trades per second but which part of the server has this speed?

I guess, it’s the accesshttp module. Is it correct?

**Comment by qyangdu** [comment]
MySQL is the bottomneck, the whole system order tps is actual about 1k.

**Comment by haipome** [comment]
It depends on the MySQL. You can move the write history part out of matchengine and use mulit mysql instance to increase the performance.
