### ISSUE TITLE
technical support and consulting（提供技术支持与咨询）

### ISSUE THREAD

**Issue by qyangdu** [viabtc/viabtc_exchange_server#193]
提供以下咨询，详情咨询QQ: 346533475
* 系统部署方案
* 交易系统优化与改进建议
* 市场行情容量改进方案
* 或整套解决方案设计

Please contact (duyang.seu AT gmail.com) for support & consulting about,
* System build and setup
* trading system tps enhancement and optimization
* support of millions of concurrent market data connections
* full trading system solution design

**Comment by insomax** [comment]
似乎报价系统在查询压力过大时经常会卡死kafka的消息，导致行情不更新，请问对与这种情况有相关尝试和优化经验吗？

**Comment by qyangdu** [comment]
因为marketprice处理请求和kafka数据是在同一个线程的，查询太忙就读不了kafka了，把marketprice中查询处理和kafka读取分离到不同线程可以解决。
