### ISSUE TITLE
get market list fail

### ISSUE THREAD

**Issue by codeman-crypto** [viabtc/viabtc_exchange_server#198]
Hi,

When I start the marketprice daemon I am getting the below error

`[2019-07-20 11:34:47.855155] [959] [error]mp_message.c:359(init_market): get market list fail`

I think there is some issue with the redis, can anyone face these type of issue

**Comment by majid-zandi** [comment]
i am getting this error too

**Comment by qyvlik** [comment]
marketprice depends_on matchengine
start matchengine first
