### ISSUE TITLE
./marketprice.exe: init message fail: -361: No such file or directory

### ISSUE THREAD

**Issue by codeman-crypto** [viabtc/viabtc_exchange_server#199]
Getting the below error message when I start the marketprice daemon

`./marketprice.exe: init message fail: -361: No such file or directory`

and the log says the below error
`[error]mp_message.c:359(init_market): get market list fail`

Can anyone help me resolve this issue, I have been struggling for more than a day

**Comment by objectt** [comment]
start matchengine first

**Comment by codeman-crypto** [comment]
@objectt  I have already started the matchingengine, looks like the marketprice is unable to fetch the market list.

**Comment by objectt** [comment]
@codeman-crypto try querying "market.list" method from marketprice server. it sends a http req to ME during startup.

**Comment by codeman-crypto** [comment]
@objectt I managed to fix this issue. Actually, I am running this on a Kubernetes cluster so each module run separately inside a docker container so I changed the order of running the container, the order are as follows
- Alertcentre
- Matching Engine
- Read History
- AccessHTTP 
- Marketprice(make sure you give the acccesshttp endpoint inside `marketprice.json` config)
- accessws

Thank you @objectt  for your help. I am closing this issue as it is resolved

**Comment by chaulaode1257** [comment]
@codeman-crypto how to use fix it?I got the same issue.
