### ISSUE TITLE
Is serialization questions. when using thread pool.

### ISSUE THREAD

**Issue by trustfarm-dev** [viabtc/viabtc_exchange_server#20]
example in ut_dict.c ,
there's widely referenced dictionary hash table generation functions.
in mp_server.c , trade , me_main.c , they uses threadpool ,
but, I can't find dict function / balance categorie (mpdecimal use) , and several global variable doesn't protected on MT-safe condition.

where can I find serialzation code? it is exists in just thread pool add/remove functions only.

**Comment by haipome** [comment]
I don't very clear your questions.

All the process are single or multi process model, not multi thread model. It only use thread do certain job, and the multi thread safe protect is in the nw_job.c.

The hole system use JSON as serialization formats. It use HTTP/WESOCKET as payload protocol, you can find it in ut_http.c and ut_ws_svr.c. It also use a binary base and self-defined RPC protocol for internal communicate, you can find it in ut_rpc.c.

**Comment by trustfarm-dev** [comment]
nw_job.c , there's thread pool manage function is MT-safe.
inside of thread function there's refer and use dict function , it looks not thread safe.
checking it please, I didn't found any lock mechanism.

and https://github.com/viabtc/viabtc_exchange_server/issues/15 , 
you commented, 

"If you have read the code, it use thread pool to write to MySQL. It won't break the server."

Where can I find your sentences , clues?

**Comment by haipome** [comment]
The code relate with the thread is written very carefully. I am sure it is safe.

You can read me_history.c, it use thead pool write SQL to DB.

**Comment by trustfarm-dev** [comment]
https://github.com/viabtc/viabtc_exchange_server/blob/3da9c872bc4b53a5f58e9254aeee2550c972a512/matchengine/me_history.c#L88
        dict_delete(dict_sql, entry->key);

it looks not MT. this code is called different context, onTimer events.
In case of onTimer expired asynchnously and different context.

**Comment by trustfarm-dev** [comment]
It may be a little bit helpful for using mutex with protecting sharable resources.
http://www.yolinux.com/TUTORIALS/LinuxTutorialPosixThreads.html
