### ISSUE TITLE
Question about matching server

### ISSUE THREAD

**Issue by bcashier** [viabtc/viabtc_exchange_server#200]
Hi,

> matchengine: This is the most important part for it records user balance and executes user order. It is in memory database, saves operation log in MySQL and redoes the operation log when start. It also writes user history into MySQL, push balance, orders and deals message to kafka.

As in memory DB, what are you using please ? is it Redis ? and what is the use case of in memory database at this stage ?

Are the orders received from REDIS and then used inside an another in memory database or ? a clear informations will be awesome please :)

Thank you

**Comment by objectt** [comment]
@bcashier  matchengine does not use redis. marketprice uses redis for storing kline info.
'in memory database' in the description implies that it internally stores(holds) all data in its memory  in various data structures.

**Comment by bcashier** [comment]
@objectt First many thanks for your answer :)

Please what do you mean by kline infos ? (sorry for my ignorance)

Can you developpe more the process used to store in memory and what kind of data stored if possible ? And important thing, why not using REDIS instead ? Why is this solution is better than other ?

Sorry for all my questions and hope I will get detailed infos since I am stuck on this long ago and I am thirsty to know more about it ... You can take the time it takes to answer, be comfortable with it.

Thank you again.

**Comment by objectt** [comment]
@bcashier 

1. What is kline?
= statistics of transactions in the given range of time (candle chart)
2.  What kind of data is stored in memory?
- information of all orders
- user balances
- market info
3. whay not use Redis instead?
= because the data must be persistent. You can use any types of database if you can manage it without losing it. MySQL is just one of many options.

**Comment by bcashier** [comment]
@objectt 

Thank you sir for your time and effort given to answer my question :)

I misunderstand you in one point: MySQL is not an In Memory DB no ?

Where are stored orders received from WEB/API before they go to MySQL database to save history ?

In my understanding, I see your matching server working like this (Correct me if I am wrong of course):
- First, get new orders from clients
- If new order don't match others, he will be added to a queue (Not yet sent to MySQL, but In Memory DB for faster performances)
- Receive another orders from clients, then check if it match other orders in a queue, if it's the case, balance will be removed from user, new order history will be create to MySQL and notify user via websocket and change market price, 24h volume etc.

Is this the process used ? I think from the schema here it's what I understand:
https://user-images.githubusercontent.com/1209350/32476113-5ffc622a-c3b0-11e7-9755-924f17bcc167.jpeg

>     What kind of data is stored in memory?
> 
>     information of all orders
>     user balances
>     market info

This datas must be stored in a MySQL database and not In memory database.

Please correct me and give me more infos if possible :)

Thank you again sir :)

**Comment by objectt** [comment]
@bcashier 

- MySQL is not an in-memory database.
- All orders are stored within the application's memory (not in a separate in-memory database). 'In-memory database' that the author is referring to is not a separate process. It means the data is held by the application within its memory.

- New orders are stored in application's memory (in a skiplist)
- Application periodically dumps current data(=status) to MySQL (loaded on startup)
- Finished(matched, cancelled) orders are immediately sent to MySQL

**Comment by bcashier** [comment]
@objectt This is what I am looking for !

Thank you sir :)
