### ISSUE TITLE
交易所/钱包-开发定制|Exchange/wallet-development/customization

### ISSUE THREAD

**Issue by An-newwork** [viabtc/viabtc_exchange_server#204]

**Comment by An-newwork** [comment]
example:
https://vipdax.vip
http://bitarq.io/

**Comment by daisyily** [comment]
之前一直担心钱包安全问题，用了优盾钱包觉得还真挺不错的，有免费版的可以试用https://www.udun.io

**Comment by VVanaheim** [comment]
现在都没人开发钱包系统了吧，麻烦耗神，感觉都在用优盾、库神之类的钱包

**Comment by Aimeelu668** [comment]
楼上说的[优盾钱包](https://www.uduncloud.com/)是这家吗？
我看了下，这个是交易所钱包，很多人在用呢
可是 我想找个人钱包 有推荐的吗

**Comment by lawrence296** [comment]
I'm looking for someone to build just the trading frontend. I have the backend all setup with websocket working. Two versions required - desktop and mobile - something like https://m.gcox.sg/#/market/exchange.
