### ISSUE TITLE
I am in trouble to install viabtc_server

### ISSUE THREAD

**Issue by ganadara135** [viabtc/viabtc_exchange_server#21]
Error Message
/root/exsv/matchengine/me_message.c:45: undefined reference to `rd_kafka_last_error'

Even if I do my best, I couldn't find any solutions up to now.
The list of what I do
1. I changed all position of options for compiling 
ex) -Wl,-Bstatic -lev -ljansson -lmpdec -lmysqlclient -lz -lrt -lstdc++ -lrdkafka -lssl -lcrypto -lhiredis -Wl,-Bdynamic -lm -lpthread -ldl
2. I changed rdkafka.h on the last version 0.94.

There are any other ways?

**Comment by ganadara135** [comment]
Add commands for compilation

gcc -g -rdynamic -o matchengine.exe  me_operlog.o  me_persist.o  me_cli.o  me_load.o  me_balance.o  me_dump.o  me_main.o  me_server.o  me_history.o  me_config.o  me_update.o  me_message.o  me_trade.o  me_market.o -L ../utils -lutils -L ../network -lnetwork -Wl,-Bstatic -lev -ljansson -lmpdec -lmysqlclient -lstdc++  -lssl -lcrypto -lhiredis  -lz -lrt -lrdkafka -Wl,-Bdynamic -lm -lpthread -ldl

**Comment by grumpydevelop** [comment]
hey, try this for compiling! :)
https://pastebin.com/PWjcfBJp

**Comment by djpnewton** [comment]
this is how i compiling it: https://github.com/djpnewton/viabtc_exchange_server/blob/ansible/provisioning/build_viaxch.yml

**Comment by infinitytn** [comment]
same here. i tried all method and it does not work. did you figure it out?

**Comment by grumpydevelop** [comment]
@infinitytn try to download rdkafka sources and compileit yourself, after that it will work
https://github.com/edenhill/librdkafka/archive/v0.11.0.tar.gz
