### ISSUE TITLE
marketprice.exe error message

### ISSUE THREAD

**Issue by ganadara135** [viabtc/viabtc_exchange_server#22]
<error message>
# ./marketprice.exe: init message fail: -309: Connection refused

Anyone know this messages reason?
I am not familiar with Redis db and C language. So I was in hardship.

**Comment by djpnewton** [comment]
see: https://github.com/viabtc/viabtc_exchange_server/blob/master/marketprice/mp_message.c#L309

you have to set up a redis sentinel and master, and make sure they are accessible to marketprice.exe

the redis sentinel config is here: https://github.com/viabtc/viabtc_exchange_server/blob/master/marketprice/config.json#L30

**Comment by ganadara135** [comment]
After I set up 3 sentinel, I works. Thanks a lot.
