### ISSUE TITLE
出售基于viabtc开发的交易所代码，帮搭建包教会，wx：wxidzhu1996

### ISSUE THREAD

**Issue by SuLinXin** [viabtc/viabtc_exchange_server#234]
出售基于viabtc开发的交易所代码，帮搭建包教会，wx：wxidzhu1996 qq：434945072

**Comment by SuLinXin** [comment]
![WechatIMG1](https://user-images.githubusercontent.com/27907712/71638624-c5e89e00-2c9f-11ea-81a3-a9e7bb816478.jpeg)

**Comment by SuLinXin** [comment]
![WechatIMG1](https://user-images.githubusercontent.com/27907712/71638630-e6185d00-2c9f-11ea-9285-b1b839b16541.jpeg)

**Comment by bigear002** [comment]
出售基于viabtc开发的交易所代码，帮搭建包教会，wx：sxonem

**Comment by dock993** [comment]
出售基于viabtc开发的交易所代码，帮搭建包教会，微信: dock993
