### ISSUE TITLE
database schema?

### ISSUE THREAD

**Issue by djpnewton** [viabtc/viabtc_exchange_server#24]
Is it possible to get some information about how the database is designed?

For instance it looks like each user in the system gets a set of their own tables (order_history_%u, order_detail_%u, deal_history_%u, user_deal_history_%u, balance_history_%u). Is there a reason for that?

**Comment by infinitytn** [comment]
i have same question.

**Comment by sheepy0905** [comment]
I think the history tables are to be auto-created with the included sql script with suffixes 1 to 99. In the code there seems to be a hashing function to determine which table a transaction should be saved to. I don't necessarily understand the reason behind such design. To me, these tables could be redone with sql partitioning.

**Comment by haipome** [comment]
The order and trade and balance history will have billions records in the long run. Simply use 100 table to reduce records number in every table. I was plan to rewrite the history system in the future if there are more records.
