### ISSUE TITLE
How do I insert asset data?

### ISSUE THREAD

**Issue by ganadara135** [viabtc/viabtc_exchange_server#26]
I got a great help from djpnewton.
However, I am in trouble to insert market data into exchange server.

I have 2 questions
one is that how to input asset data.
two is that if accessws server is the one to insert data, how do I use it?  how do I install it?

**Comment by djpnewton** [comment]
accessws does not insert data.. it should be read only and only used for subscribing to receive events

all the RPCs go through accesshttp
