### ISSUE TITLE
[wiki] balance.history request business type is wrong

### ISSUE THREAD

**Issue by ceyonur** [viabtc/viabtc_exchange_server#267]
Hello,
I'm trying to write a openrpc schema for the viabtc APIs. 

It indicates `business: business，which can be null，use ',' to separate types`, however in the code https://github.com/viabtc/viabtc_exchange_server/blob/08c0eb4a4427fa665e215b990ba10fc2dac73d37/readhistory/rh_reader.c#L27 there is no "like" operator or multiple clauses seperated by `,`. Am I missing something or wiki is wrong?

**Comment by haipome** [comment]
The origin design is support multi business, but it may slow down the query speed, so remove this support.
