### ISSUE TITLE
内存不够挂掉后，无法恢复现场

### ISSUE THREAD

**Issue by TaylorWenOne** [viabtc/viabtc_exchange_server#279]
测试时，运行了几天，内存升高达到极限，然后重启，发现恢复不了现场
这个ws请求始终报错："internal error"（重启via多次仍然如此）
请问该如何解决

    var _sendContent = JSON.stringify({

                            id : 4,
                            method : 'deals.query',
                            params : [marketSymbol, 36, 0]
                        });

**Comment by TaylorWenOne** [comment]
> 测试时，运行了几天，内存升高达到极限，然后重启，发现恢复不了现场
> 这个ws请求始终报错："internal error"（重启via多次仍然如此）
> 请问该如何解决
> 
> ```
> var _sendContent = JSON.stringify({
> 
>                         id : 4,
>                         method : 'deals.query',
>                         params : [marketSymbol, 36, 0]
>                     });
> ```

好吧，我解决了，redis问题，好像是我把order_detail表和一些history清空了引发的问题，我把redis也清空了，重启就好了，只是历史k线没有了。。

**Comment by raiseu** [comment]
交易所提供技术支持，出售币币，OTC，合约交易所全套代码，可以二次开发，有客户案例 wx: doposn

**Comment by exchange-server** [comment]
https://github.com/exchange-server/futures-viabtc-exchange

**Comment by viabtcphp** [comment]
https://github.com/viabtcphp/viabtc_exchange_php 基于ves的币币合约交易所开源版
