### ISSUE TITLE
写了一个基于ves的币币合约交易所，欢迎大家指导

### ISSUE THREAD

**Issue by viabtcphp** [viabtc/viabtc_exchange_server#284]
https://github.com/viabtcphp/viabtc_exchange_php 基于ves的币币合约交易所开源版

**Comment by 2981511958** [comment]
盗源码也盗得这么理直气壮，你这仓库整整比我晚4个月，好意思说自己写的？

开源不易，请大家认准作者
源仓库：https://github.com/2981511958/php_chain_exchange
