### ISSUE TITLE
marketprice.exe: init message fail

### ISSUE THREAD

**Issue by empire1999** [viabtc/viabtc_exchange_server#29]
**marketprice.exe: init message fail: -309: Operation now in progress**
Anyone know this messages reason?

**I set up three sentinel, it doesn't work!**
----------------------------------------------
$ ps -ef|grep redis
redis     6213     1  0 00:36 ?        00:00:00 /usr/bin/redis-server 127.0.0.1:6381         
redis     6223     1  0 00:36 ?        00:00:00 /usr/bin/redis-server 127.0.0.1:6382         
redis     6231     1  0 00:36 ?        00:00:00 /usr/bin/redis-server 127.0.0.1:6383         
redis     6244     1  0 00:36 ?        00:00:00 /usr/bin/redis-sentinel *:26381                   
redis     6254     1  0 00:36 ?        00:00:00 /usr/bin/redis-sentinel *:26382                   
redis     6264     1  0 00:36 ?        00:00:00 /usr/bin/redis-sentinel *:26383                   
deploy    6274  3049  0 00:37 pts/8    00:00:00 grep --color=auto redis

$ redis-cli -p 6381 info | grep role
role:master
$ redis-cli -p 6382 info | grep role
role:slave
$ redis-cli -p 6383 info | grep role
role:slave

$ redis-cli -p 26381 -h 127.0.0.1 INFO Sentinel
sentinel_masters:1
sentinel_tilt:0
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
master0:name=mymaster,status=ok,address=127.0.0.1:6381,slaves=2,sentinels=3

**Comment by djpnewton** [comment]
> marketprice.exe:  init message fail: -309: Operation now in progress

This means that the failure occurred in line 309 of `mp_message.c`. So the call to  `redis_sentinel_connect_master()` failed, you could try putting some logging in that function to see why it fails, also take a look at your `marketprice/config.json` file and double check redis connection settings (try using telnet to see you can connect to the host)

**Comment by empire1999** [comment]
The error is "unknown command 'ROLE'". I upgrade redis-server to a version after 2.8.12. It's OK. 
Thank you very much.
