### ISSUE TITLE
Update balance

### ISSUE THREAD

**Issue by grumpydevelop** [viabtc/viabtc_exchange_server#34]
Hello!
How to add coin daemons support to your exchange server?
Thx, max
;)

**Comment by taylorshuang** [comment]
Me too. How to add a coin daemon attached this exchange server?any example for us？

**Comment by djpnewton** [comment]
I think that is outside of the scope of this project (similar to say validating fiat deposits/withdrawals).

You will need some sort of external wallet module that bridges the coin daemon and the viabtc exchange asset API (accesshttp.exe  "balance.update" etc).

**Comment by grumpydevelop** [comment]
@djpnewton i have python frontend builded on flask, i made daemon that checks balance from coin daemon and sends it to daemon, but there is problem that balance.update sum up, i need to balance.update makes balance equal instead of sum

**Comment by grumpydevelop** [comment]
@djpnewton https://pastebin.com/67BqxRMH

**Comment by djpnewton** [comment]
ok, well short of adding a new RPC to viabtc_exchange_server you could:

- track individual transactions from the coin daemon instead of the entire balance
- query the exchange balance first (balance.query) and send "balance.update" the difference (you would have to think about data races with this method though)

**Comment by grumpydevelop** [comment]
I updated code! Will u add my balance checker code written in python to your exchange?

**Comment by grumpydevelop** [comment]
I think that it will be very helpful to other peoples

**Comment by grumpydevelop** [comment]
@djpnewton https://imgur.com/a/0dY4s

**Comment by grumpydevelop** [comment]
it updates only when daemon balance changed

**Comment by grumpydevelop** [comment]
https://github.com/grumpydevelop/viabtc_exchange_server_tools
