### ISSUE TITLE
关于安装viabtc_exchange_server的问题.

### ISSUE THREAD

**Issue by mymixing** [viabtc/viabtc_exchange_server#38]
首先谢谢作者的开源.
在部署viabtc_exchange_server过程忠,目前碰到两个问题想请教一下作者.

1 marketprice中redis_sentinel_connect_master会被定时调用获取redis主节点,
代码中我并没有找到对于redis_sentinel_connect_master的定时器发起点,
所以只能猜测这个定时器只是单纯用来时刻获取主节点的.
但从netstat看来,这个连接并没有长链,都是发起一次关闭一次的.
所以想请问,这个行为是正确的吗?

2.matchengine启动时报错
[2017-11-27 10:30:37.701069] [11483] [error]me_persist.c:96(load_operlog_from_db): table operlog_20171127 not exist
这是正常的吗?
如果不正常,是否是要做个定时任务每天根据operlog_example来创建operlog_ymd表?

**Comment by haipome** [comment]
1、https://github.com/viabtc/viabtc_exchange_server/blob/master/marketprice/mp_message.c#L788 这个函数会定期执行，用于持久化 K 线数据到 Redis.
2、operlog_example 表需要手动创建。可以根据 https://github.com/viabtc/viabtc_exchange_server/blob/master/sql/create_trade_log.sql 这个文件进行创建

**Comment by mymixing** [comment]
谢谢.

**Comment by gyk001** [comment]
给viabtc_exchange_server做了一组docker compose配置，方便刚接触的人快速跑起来。
地址如下： https://github.com/gyk001/viabtc_exchange_server_docker

**Comment by lealife** [comment]
在Centos下搭建成功, 文档链接:
https://github.com/lealife/viabtc_exchange_server/issues/1
