### ISSUE TITLE
Different results from market.status_today and market.status (period=86400), expected?

### ISSUE THREAD

**Issue by AndrewSamokhvalov** [viabtc/viabtc_exchange_server#39]
Hello @haipome! Could you please elaborate should the responses from `market.status_today` and `market.status` with `period=86400` return different results?

```
(*core.MarketStatusTodayResponse)({
 Open: "0.18158999",  <--- different
 High: "0.19",
 Low: "0.12",  <--- different
 Amount: "355834.6932008347845013",
 Volume: "2203265.3882346"
 Last: "0.16988683",
})
(*core.MarketStatusResponse)({
 Open: "0.17310776", <--- different
 Close: "0.16988683",
 High: "0.19", 
 Low: "0.1111",  <--- different
 Volume: "2203265.3882346"
 Last: "0.16988683",
 Period: 86400,
})
```

**Comment by haipome** [comment]
@AndrewSamokhvalov 
The `market.status` return relative time.
The `market.status_today` behavior is a little strange, The open/close/high/low is in calendar today, which is absolute time base on the server local time. But the Volume and Amount is base the relative time. This method will be removed.

**Comment by AndrewSamokhvalov** [comment]
Got it, thanks! But how the behaviour of the websocket subscription `today.update` will be changed in this case? Would it be transformed in `market.update` or something? 🤔 

And it would be really great if you have an time estimation for this change.

**Comment by haipome** [comment]
I will add one state.query state.subscribe state.unsubscribe method.
