### ISSUE TITLE
accessws, depth.updates, interval len("0.00000001") >= INTERVAL_MAX_LEN

### ISSUE THREAD

**Issue by AndrewSamokhvalov** [viabtc/viabtc_exchange_server#40]
Hey @haipome, I believe that in order to subscribe on `depth.update` in `accessws` with interval `0.00000001` (which is specified as available in `config.json`) we have to make [INTERVAL_MAX_LEN](https://github.com/viabtc/viabtc_exchange_server/blob/283fc3ea48ebf8ee792c5be5f51d05fc133868e4/accessws/aw_config.h#L43) a bit bigger, or am I missing something?

**Comment by haipome** [comment]
Yes, I will change this a little bigger.
