### ISSUE TITLE
关于订单权限问题.

### ISSUE THREAD

**Issue by mymixing** [viabtc/viabtc_exchange_server#41]
@haipome 你好.
正在学习您的项目,现在刚刚部署完成,
产生了新的疑问.
项目里貌似没有用户管理这一块的服务.
通过accesshttp能直接对户资产进行更改.
是否是说accesshttp不能直接对外进行服务,
所有接口只对内网的用户类webserver连接开放?
想请教下设计思路,谢谢.

**Comment by haipome** [comment]
你可以看一下 readme 里面的架构图，accesshttp 是不直接面对用户的，接口也是内网的。用户管理属于 web 端的任务。accessws 是直接面向用户的。

**Comment by haipome** [comment]
整个系统只负责记录用户的余额，执行订单，记录订单、资金历史，生成和推送行情等任务。使用 user_id 来表示用户。user_id 由 web 进行维护。

**Comment by mymixing** [comment]
谢谢.
