### ISSUE TITLE
Some questions about the project

### ISSUE THREAD

**Issue by egorsmkv** [viabtc/viabtc_exchange_server#43]
Hello, haipo!

I have some questions about your project https://github.com/viabtc/viabtc_exchange_server

I will be happy if you answer these questions:

1. Firstly, I didn't see the ViaBTC when it was working and I don't know how much people use it. My question is: why do you use MySQL?
Maybe, a preferred database will be MongoDB or another NoSQL database? I know about the persistence, so we can enable it in MongoDB.

2. Which was the load on the system when the ViaBTC was working?

3. Why did you use the C? Is it your the main programming language?

Thanks!

**Comment by haipome** [comment]
1. Why do you think MongoDB is better choice?
2. ViaBTC exchange online for about 4 months and shout down by the china gov. We are growing fast, but the load is very low.
3. C is the highest performance program language, and is perfect for in memory databases.

**Comment by egorsmkv** [comment]
> Why do you think MongoDB is better choice?

With MongoDB we can use [Data Partitioning with Chunks](https://docs.mongodb.com/v3.4/core/sharding-data-partitioning/) or [Partitioned Collections](https://www.percona.com/blog/2014/05/29/introducing-partitioned-collections-for-mongodb-applications/) when your decision is a few tables for that.

> C is the highest performance program language, and **is perfect for in memory databases**.

Can you explain this? How does this apply to your project?
