### ISSUE TITLE
no "total" field for order.completed RPC

### ISSUE THREAD

**Issue by djpnewton** [viabtc/viabtc_exchange_server#45]
The order.pending RPC returns a "total" field (indicating the total number of records that one could request using the offset and limit fields) but order.completed does not have this field (same with balance.history)

Looking at the code I guess we could do a "SELECT count()" type query as well (in rh_reader.c get_user_order_finished()).. but I guess it could add a bit more load to the server

**Comment by haipome** [comment]
Yes, The reason is to reduce the load of the server. The total is not necessary for history data in fact. Just always use next page or prev page.

**Comment by djpnewton** [comment]
ok, thanks for confirming that suspicion
