### ISSUE TITLE
Dependency configuration

### ISSUE THREAD

**Issue by sheepy0905** [viabtc/viabtc_exchange_server#46]
Hi Haipo,

Could you please share the configuration and setup instructions for Zookeeper, Kafka, and Redis server+sentinel?

Thanks.

**Comment by djpnewton** [comment]
take a look at this branch which uses ansible/vagrant to build and setup all the servers: https://github.com/djpnewton/viabtc_exchange_server/tree/ansible

**Comment by sheepy0905** [comment]
Hi @djpnewton , could you please elaborate on how you set up vagrant? I was able to compile and run all servers in dev environment (with libmysqlclient-dev dynamically linked). However, I had trouble running matchengine.exe on a remotely deployed server, even though I had apt-get install libmysqlclient-dev on that one. I have very little working experience with c :(

**Comment by djpnewton** [comment]
in my branch shown, you should just be able to run "vagrant up" and it will build and configure all the required servers needed so you can then run a test front end (like - https://github.com/djpnewton/viaxchtest)

**Comment by haipome** [comment]
@sheepy0905 You can check project documents.

**Comment by sheepy0905** [comment]
@djpnewton thanks for the explanation. I am running windows dev host and ubuntu virtualbox to do this dev work. I guess I am out of luck to setup another vm inside my ubuntu vm :(

**Comment by djpnewton** [comment]
you can use vagrant/ansible/virtualbox directly from windows. Just make sure your windows text editors use unix line endings when editing shell scripts etc
