### ISSUE TITLE
Hi Haipo, is it possible to get installation service from you ?

### ISSUE THREAD

**Issue by HermantoSardan** [viabtc/viabtc_exchange_server#49]
Hi Haipo,

Glad to see you still maintain this viabtc_exchange_server script even your exchange business was closed due to government regulation

I am working to setup my exchange business and looking for industrial standard and well tested software for the exchange server and may use via BTC

Could you please advise if possible to me to get support from your side ?, we can do good exchange business

Lookign forward for your reply

Thank you

Regards,
Sardan

**Comment by chengloy** [comment]
The same to me

**Comment by rakabod1** [comment]
i would also be looking for this service from you

**Comment by grumpydevelop** [comment]
@HermantoSardan @chengloy @rakabod1 pm me in telegram @maxzambinq i can help u

**Comment by lingdu0001** [comment]
I have installed all the depence.
But there is some errors, would you please help me?
Thank you !
The log is:
process: matchengine version: 0.1.0, compile date: Jan 31 2018 09:21:14
bin/matchengine.exe: init process fail: -36: Operation not permitted
