### ISSUE TITLE
限价单逻辑是否反了？

### ISSUE THREAD

**Issue by wuwei0509** [viabtc/viabtc_exchange_server#53]
在execute_limit_ask_order里，判断
> if (mpd_cmp(taker->price, maker->price, &mpd_ctx) > 0) {
>       break;
> }

这样的话，挂买单，撮合的都是卖价大于等于买价的，买贵了。
在execute_limit_bid_order里则是
> if (mpd_cmp(taker->price, maker->price, &mpd_ctx) < 0) {
>       break;
>  }
这个，挂卖单，撮合的也是买价小于等于卖价的，卖便宜了。

**Comment by haipome** [comment]
ask 是卖，bid 是买
