### ISSUE TITLE
operlog not exist

### ISSUE THREAD

**Issue by bitcoinli** [viabtc/viabtc_exchange_server#55]
Hi, I get this error when I run matchengine.

table operlog_20180125 not exist
table operlog_20180126 not exist

![image](https://user-images.githubusercontent.com/29343319/35428213-d96d1fa2-027e-11e8-9afd-a19893ea222e.png)

**Comment by haipome** [comment]
This is normal.

**Comment by bitcoinli** [comment]
@haipome Thank you for your reply.

why do we get this error ?

**Comment by haipome** [comment]
because you start at the first time, the operlog dost not exist.
