### ISSUE TITLE
frontend and web api

### ISSUE THREAD

**Issue by bitcoinli** [viabtc/viabtc_exchange_server#56]
Hi,

How can we do frontend and web API?

**Comment by kievking** [comment]
if you're asking this question, probably you shouldn't try to open an exchange. It's a hard business.

**Comment by bitcoinli** [comment]
@kievking , preliminary information is required. Is there a working example?

**Comment by kievking** [comment]
Not really, i don't think he posted code for frontend and api. you can develop those yourself according the documentation of the backend.

**Comment by ilanoh** [comment]
Is there a working exchange using this backend ?

**Comment by grumpydevelop** [comment]
guys, if you need frontend you can write me in telegram: @lspidh

**Comment by ohld** [comment]
@grumpydevelop I can't find you on telegram, perhaps you have changed your nickname.

**Comment by burseekdev** [comment]
@ohld @greypoigvm

**Comment by burseekdev** [comment]
@ohld i can sell u frontend

**Comment by melmali2828** [comment]
@burseekdev  telegram or skype nick ?

**Comment by burseekdev** [comment]
@ohld @melmali2828 telegram

**Comment by ohld** [comment]
I don't want to buy frontend. I'd like to see code snippets how to register users, make orders, visualise order book etc.
