### ISSUE TITLE
请问me_persist.c中的dump_to_db是如何保证operlog_id_start与dump的order和balance的一致性？

### ISSUE THREAD

**Issue by zhou4737** [viabtc/viabtc_exchange_server#58]
int dump_to_db(time_t timestamp)函数中先执行了dump_order_to_db、dump_balance_to_db然后使用update_slice_history记录当前的operlog_id。是否可能导致记录的operlog_id大于dump_order_to_db、dump_balance_to_db时的实际id，在恢复数据时导致漏执行operlog？

**Comment by haipome** [comment]
执行 make_slice 之前进行了 fork, 由 fork 出来的子进程来处理数据的 dump。fork 之后子进程数据不会再变，不受主进程的影响。

**Comment by zhou4737** [comment]
谢谢解惑

**Comment by lealife** [comment]
这种方法很巧妙, 如果用其它语言怎么实现呢? 比如Python, golang, java?
只能先深度拷贝orders, balances, 然后再异步写数据库?

```
lock()
copy all orders, balances
unlock()
dump to db async
```
