### ISSUE TITLE
balance update return repeat update

### ISSUE THREAD

**Issue by mikezit** [viabtc/viabtc_exchange_server#72]
你好： 
第一次运行结果
./cli.exe 192.168.0.100 7316 102 '[1, "LTC", "deposit", 10001, "100000",{}]'
{
    "id": 0,
    "error": null,
    "result": {
        "status": "success"
    }
}

第二次得到
./cli.exe 192.168.0.100 7316 102 '[1, "LTC", "deposit", 10001, "100000",{}]'
{
    "id": 0,
    "error": {
        "message": "repeat update",
        "code": 10
    },
    "result": null
}

查看代码是下面返回了-1
int update_user_balance(bool real, uint32_t user_id, const char *asset, const char *business, uint64_t business_id, mpd_t *change, json_t *detail)
{
    struct update_key key;
    key.user_id = user_id;
    strncpy(key.asset, asset, sizeof(key.asset));
    strncpy(key.business, business, sizeof(key.business));
    key.business_id = business_id;

    dict_entry *entry = dict_find(dict_update, &key);
    if (entry) {
        return -1;
    }
 ..........

请问这样设计的逻辑是什么？

///////////
另外，是否有情况发生这样的事，有人攻破进入martchmachine部署的服务器,随意修改balance,然后随意下单，引起市场价格剧烈波动。

感谢。

**Comment by sheepy0905** [comment]
防止重复入账。

**Comment by mikezit** [comment]
问题是，如果真的是连续充值同一个币种两次，怎么处理呢？

**Comment by yuliyuanchn** [comment]
"deposit", 10001
這兩個參數，第一個是業務類型，第二個是業務ID，如果都是充值，換個業務ID就可以了

**Comment by mikezit** [comment]
业务类型和业务ID是对应的吧，你的意思是10001是递增的？
