### ISSUE TITLE
How to add second, third main trade currency

### ISSUE THREAD

**Issue by vsolodovnyk** [viabtc/viabtc_exchange_server#75]
Now in exchange server there is only one main trade currency - BCH, all assets are trading against BCH. How can I add BTC, ETH, USD, EUR or more currencies for trading pairs.
For example, now I can trade only ETH/BCH, but I want to trade ETH/USD, ETH/BTC or may be even ETH/NEO. Could anybody help ?

**Comment by grumpydevelop** [comment]
write me in telegram @lspidh

**Comment by sheepy0905** [comment]
you can add new trading asset and pairs in the config.json for matchengine.exe. Take a look yourself. it's a very easy thing.

**Comment by vsolodovnyk** [comment]
Could you please share working "config.json", because when I change config, I got errors:
```
./matchengine.exe: init trade fail: -47
./marketprice.exe: init message fail: -361: No such file or directory

```

**Comment by sheepy0905** [comment]
can you read code?
this is why it's happening:
https://github.com/viabtc/viabtc_exchange_server/blob/12b8c4c0ebfddbffface8a907856cbdbd6a3d3b5/matchengine/me_market.c#L259

**Comment by vsolodovnyk** [comment]
Thanks !
If you want to add two or more "money" currency, you need:
1) preс = 20 for this currency
2) add pair between main currencies, e.g. BTC/USD if adding BTC and USD as "money" currency in market. Otherwise errors occur.

**Comment by ravituduru** [comment]
> you can add new trading asset and pairs in the config.json for matchengine.exe. Take a look yourself. it's a very easy thing.

Can please tell explain me with an example.

**Comment by grumpydevelop** [comment]
@ravituduru if u still need help message me cypper@pm.me
