### ISSUE TITLE
引擎是否支持多实例，以支持不同的交易对

### ISSUE THREAD

**Issue by qyvlik** [viabtc/viabtc_exchange_server#79]
引擎是否支持多实例，以支持不同的交易对

就现在来看，应该单个引擎支持多个交易对。@haipome

> One single instance is given for matchengine, marketprice and alertcenter, while readhistory, accesshttp and accwssws can have multiple instances to work with loadbalancing.
> https://github.com/viabtc/viabtc_exchange_server#compile-and-install

**Comment by sheepy0905** [comment]
建议先学习配置文件再发问。

**Comment by qyvlik** [comment]
@sheepy0905 好的，谢谢建议
