### ISSUE TITLE
Issue in building on linux OS ubuntu 14.04

### ISSUE THREAD

**Issue by iamsrivastava** [viabtc/viabtc_exchange_server#85]
/usr/include/endian.h:77:0: note: this is the location of the previous definition
 #  define le64toh(x) __uint64_identity (x)
 
gcc -g -rdynamic -o matchengine.exe  me_persist.o  me_cli.o  me_load.o  me_balance.o  me_dump.o  me_operlog.o  me_server.o  me_main.o  me_trade.o  me_config.o  me_update.o  me_history.o  me_message.o  me_market.o -L ../utils -lutils -L ../network -lnetwork -Wl,-Bstatic -lev -ljansson -lmpdec -lmysqlclient -lz -lrdkafka -lssl -lcrypto -lhiredis -Wl,-Bdynamic -lm -lpthread -ldl
/usr/bin/x86_64-linux-gnu-ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libev.a(ev.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
../makefile.inc:16: recipe for target 'matchengine.exe' failed
make: *** [matchengine.exe] Error 1

**Comment by johnngo** [comment]
I received the same error as well when I was trying to compile the matchengine file, any luck with resolving it?

**Comment by muhaozhang** [comment]
i meet the same problem.i fixed it with move -lev to last.
